### ISSUE TITLE
Error when trying to play remote midi

### ISSUE THREAD

**Issue by xunto** [EngineMachiner/HonkyTones#4]
```
java.lang.NoClassDefFoundError: okio/Source
	at com.squareup.okhttp.Call.getResponse(Call.java:275)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.enginemachiner.honkytones.sound.DirectAudioStream.<init>(AudioStreaming.kt:44)
	at com.enginemachiner.honkytones.sound.ExternalSound.getAudioStream(AudioStreaming.kt:139)
	at com.enginemachiner.honkytones.sound.ExternalSound.init(AudioStreaming.kt:117)
	at com.enginemachiner.honkytones.sound.ExternalSound.<init>(AudioStreaming.kt:105)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer.loadSound(MusicPlayerBlock.kt:724)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer.playSound(MusicPlayerBlock.kt:712)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer.play(MusicPlayerBlock.kt:742)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer$actions$1.invoke(MusicPlayerBlock.kt:646)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer$actions$1.invoke(MusicPlayerBlock.kt:646)
	at com.enginemachiner.honkytones.blocks.musicplayer.MusicPlayer$Companion.networking$lambda$17$lambda$16(MusicPlayerBlock.kt:1196)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)

```
We are using the latest mod version for 1.19.2: https://modrinth.com/mod/honkytones/version/mc1.19.2-v1.4.0.2

MIDI link: https://cdn.discordapp.com/attachments/962730731967217724/1195495333501861968/pillar.mid?ex=65b432ca&is=65a1bdca&hm=1f5ce6038a37b073e313f7ace11acf4d8f364684548302faf01f9eea19699416&

**Comment by xunto** [comment]
@EngineMachiner great mod, btw!

**Comment by EngineMachiner** [comment]
Hello, thanks for your words and feedback. Included dependencies in Fabric don't add nested dependencies by default so I had to add them manually to the gradle file. cad0af0 7977e8f 07a8a2e

This has been fixed in the repository and will be in the next update. I just tested your midi file and it works.
